### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by teaddicted** [harshilpatel312/KITTI-distance-estimation#1]
Hey,

Is there any result-video to see how this will actually perform? I mean if the distances are correctly predicted?

Also, is there a pre-trained model available for testing?

Thanks.

**Comment by harshilpatel312** [comment]
Hey, 

Couldn't generate the video because the data is shuffled. But I generated ran the model on images and the results are [here](https://drive.google.com/open?id=1Gj1myciopPGS-eC9ksFz5LlD7GTP00nS).

Tell me if you're not able to view the images, I will update permissions.
