### ISSUE TITLE
about distance？

### ISSUE THREAD

**Issue by codermckee** [harshilpatel312/KITTI-distance-estimation#4]
Does it just predict distance in Z axis? and I feel the distance a little bit far

**Comment by harshilpatel312** [comment]
Yes, it does predict distance in Z axis (in the direction of car's travel). 

I didn't get the second part of your question? The result images show that the actual and predicted distances are pretty close. If you train the model with more data, you'll get better results.

**Comment by BattleZhan** [comment]
> 它只是预测Z轴的距离吗？而且我觉得距离有点远

您好，可以请教您一个问题吗？我这边代码没有跑起来
